### ISSUE TITLE
Unable to clone and run the app

### ISSUE THREAD

**Issue by witbybit** [sibelius/victory-native-demo-crna#2]
I tried to run the app after cloning the repository but I got the following error:-
"console.error: fontFamily 'Menlo' is not a system font and has not been loaded through Exponent.Font.loadAsync."

![screenshot_20170327-131247](https://cloud.githubusercontent.com/assets/5186055/24345809/74c1d4a0-12ef-11e7-96e7-0dd1dacc1d99.png)

**Comment by sibelius** [comment]
could you send a PR, removing this fontFamily https://github.com/sibelius/victory-native-demo-crna/blob/2251e1f12c4b6457dff94e2327cf53438a137507/App.js#L38 ?

**Comment by witbybit** [comment]
Thanks for the reply. I can definitely do that but there is another issue that occurs after removing that line - "Error while updating property 'd' in shadow node of type: RNSVGPath"
![screenshot_20170327-161515](https://cloud.githubusercontent.com/assets/5186055/24352902/03849696-1309-11e7-8d77-d798cdb8fb57.png)

**Comment by witbybit** [comment]
I took a look at the native-component-list app as mentioned by @dikaiosune in https://github.com/react-community/create-react-native-app/issues/121
I was able to make that app work on local android emulator but I noticed that there are some strange versions used in package.json (https://github.com/expo/native-component-list/blob/master/package.json):-

```
"dependencies": {
    "@expo/ex-navigation": "2.9.3",
    "@expo/samples": "^1.0.3",
    "expo": "15.0.2",
    "gl-mat4": "^1.1.4",
    "hsv2rgb": "^1.1.0",
    "react": "~15.4.2",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-15.tar.gz",
    "regl": "^1.3.0",
    "victory-native": "0.6.0"
  }
```

Why is react-native version a url? What version number should we actually use here?
Also victory-native version seems pretty old since the current version appears to be 0.7.2.

**Comment by sibelius** [comment]
@nikhilag feel free send a PR fixing this

**Comment by witbybit** [comment]
@sibelius I really want to fix this but I am trying to figure out how. As of now, no matter what version i use in package.json, victory-native doesn't work with crna. I keep getting the error that I posted above. I haven't tried the package.json used in native-component-list yet but it doesn't seem the correct approach. Why are they using a custom url for react-native and why are they using an old version of victory-native?

**Comment by sibelius** [comment]
I think they are using an old version of react-native-svg, so this is probably breaking the new version of victory-native

**Comment by anp** [comment]
@nikhilag the Expo client usually has a ~1 week delay from a stable React Native release, I expect RN 0.43 support will be released early next week. By default Expo projects use a fork of RN so that we can ship important bugfixes early if need be, but both "vanilla" RN from npm and the Expo fork tarball should work just fine.

I suspect the old version of victory-native is because that's the version that's compatible with the react-native-svg we ship in the client app, but I could be wrong. Maybe @brentvatne can fill in with details there?

**Comment by witbybit** [comment]
Is support for 0.43 coming soon? 
@brentvatne Please comment on what versions are needed for victory-native to work with create-react-native-app. 
Thanks.

**Comment by brentvatne** [comment]
hello! I added victory-native to an expo examples repo here: https://github.com/expo/examples/tree/master/with-victory-native

**Comment by sibelius** [comment]
looks good tks
